// Code generated by entc, DO NOT EDIT.

package billstatus

const (
	// Label holds the string label denoting the billstatus type in the database.
	Label = "bill_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBillStatus holds the string denoting the billstatus field in the database.
	FieldBillStatus = "bill_status"

	// EdgeBills holds the string denoting the bills edge name in mutations.
	EdgeBills = "bills"

	// Table holds the table name of the billstatus in the database.
	Table = "bill_status"
	// BillsTable is the table the holds the bills relation/edge.
	BillsTable = "bills"
	// BillsInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BillsInverseTable = "bills"
	// BillsColumn is the table column denoting the bills relation/edge.
	BillsColumn = "billstatus_id"
)

// Columns holds all SQL columns for billstatus fields.
var Columns = []string{
	FieldID,
	FieldBillStatus,
}
