// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Bill is the predicate function for bill builders.
type Bill func(*sql.Selector)

// BillStatus is the predicate function for billstatus builders.
type BillStatus func(*sql.Selector)

// PayType is the predicate function for paytype builders.
type PayType func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// PaymentStatus is the predicate function for paymentstatus builders.
type PaymentStatus func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
