// Code generated by entc, DO NOT EDIT.

package paymentstatus

const (
	// Label holds the string label denoting the paymentstatus type in the database.
	Label = "payment_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPaymentStatus holds the string denoting the paymentstatus field in the database.
	FieldPaymentStatus = "payment_status"

	// EdgePayments holds the string denoting the payments edge name in mutations.
	EdgePayments = "payments"

	// Table holds the table name of the paymentstatus in the database.
	Table = "payment_status"
	// PaymentsTable is the table the holds the payments relation/edge.
	PaymentsTable = "payments"
	// PaymentsInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	PaymentsInverseTable = "payments"
	// PaymentsColumn is the table column denoting the payments relation/edge.
	PaymentsColumn = "paymentstatus_id"
)

// Columns holds all SQL columns for paymentstatus fields.
var Columns = []string{
	FieldID,
	FieldPaymentStatus,
}

var (
	// PaymentStatusValidator is a validator for the "PaymentStatus" field. It is called by the builders before save.
	PaymentStatusValidator func(string) error
)
