// Code generated by entc, DO NOT EDIT.

package paymentstatus

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/theuo/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PaymentStatus applies equality check predicate on the "PaymentStatus" field. It's identical to PaymentStatusEQ.
func PaymentStatus(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusEQ applies the EQ predicate on the "PaymentStatus" field.
func PaymentStatusEQ(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusNEQ applies the NEQ predicate on the "PaymentStatus" field.
func PaymentStatusNEQ(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusIn applies the In predicate on the "PaymentStatus" field.
func PaymentStatusIn(vs ...string) predicate.PaymentStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PaymentStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPaymentStatus), v...))
	})
}

// PaymentStatusNotIn applies the NotIn predicate on the "PaymentStatus" field.
func PaymentStatusNotIn(vs ...string) predicate.PaymentStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PaymentStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPaymentStatus), v...))
	})
}

// PaymentStatusGT applies the GT predicate on the "PaymentStatus" field.
func PaymentStatusGT(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusGTE applies the GTE predicate on the "PaymentStatus" field.
func PaymentStatusGTE(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusLT applies the LT predicate on the "PaymentStatus" field.
func PaymentStatusLT(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusLTE applies the LTE predicate on the "PaymentStatus" field.
func PaymentStatusLTE(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusContains applies the Contains predicate on the "PaymentStatus" field.
func PaymentStatusContains(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusHasPrefix applies the HasPrefix predicate on the "PaymentStatus" field.
func PaymentStatusHasPrefix(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusHasSuffix applies the HasSuffix predicate on the "PaymentStatus" field.
func PaymentStatusHasSuffix(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusEqualFold applies the EqualFold predicate on the "PaymentStatus" field.
func PaymentStatusEqualFold(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPaymentStatus), v))
	})
}

// PaymentStatusContainsFold applies the ContainsFold predicate on the "PaymentStatus" field.
func PaymentStatusContainsFold(v string) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPaymentStatus), v))
	})
}

// HasPayments applies the HasEdge predicate on the "payments" edge.
func HasPayments() predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentsWith applies the HasEdge predicate on the "payments" edge with a given conditions (other predicates).
func HasPaymentsWith(preds ...predicate.Payment) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.PaymentStatus) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentStatus) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentStatus) predicate.PaymentStatus {
	return predicate.PaymentStatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
