// Code generated by entc, DO NOT EDIT.

package payment

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddDatetime holds the string denoting the adddatetime field in the database.
	FieldAddDatetime = "add_datetime"

	// EdgePaytype holds the string denoting the paytype edge name in mutations.
	EdgePaytype = "paytype"
	// EdgePaymentstatus holds the string denoting the paymentstatus edge name in mutations.
	EdgePaymentstatus = "paymentstatus"
	// EdgeBill holds the string denoting the bill edge name in mutations.
	EdgeBill = "bill"

	// Table holds the table name of the payment in the database.
	Table = "payments"
	// PaytypeTable is the table the holds the paytype relation/edge.
	PaytypeTable = "payments"
	// PaytypeInverseTable is the table name for the PayType entity.
	// It exists in this package in order to avoid circular dependency with the "paytype" package.
	PaytypeInverseTable = "pay_types"
	// PaytypeColumn is the table column denoting the paytype relation/edge.
	PaytypeColumn = "paytype_id"
	// PaymentstatusTable is the table the holds the paymentstatus relation/edge.
	PaymentstatusTable = "payments"
	// PaymentstatusInverseTable is the table name for the PaymentStatus entity.
	// It exists in this package in order to avoid circular dependency with the "paymentstatus" package.
	PaymentstatusInverseTable = "payment_status"
	// PaymentstatusColumn is the table column denoting the paymentstatus relation/edge.
	PaymentstatusColumn = "paymentstatus_id"
	// BillTable is the table the holds the bill relation/edge.
	BillTable = "payments"
	// BillInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BillInverseTable = "bills"
	// BillColumn is the table column denoting the bill relation/edge.
	BillColumn = "bill_id"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldAddDatetime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Payment type.
var ForeignKeys = []string{
	"bill_id",
	"paytype_id",
	"paymentstatus_id",
}
