// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/bill"
	"github.com/theuo/app/ent/billstatus"
)

// BillStatusCreate is the builder for creating a BillStatus entity.
type BillStatusCreate struct {
	config
	mutation *BillStatusMutation
	hooks    []Hook
}

// SetBillStatus sets the BillStatus field.
func (bsc *BillStatusCreate) SetBillStatus(s string) *BillStatusCreate {
	bsc.mutation.SetBillStatus(s)
	return bsc
}

// AddBillIDs adds the bills edge to Bill by ids.
func (bsc *BillStatusCreate) AddBillIDs(ids ...int) *BillStatusCreate {
	bsc.mutation.AddBillIDs(ids...)
	return bsc
}

// AddBills adds the bills edges to Bill.
func (bsc *BillStatusCreate) AddBills(b ...*Bill) *BillStatusCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bsc.AddBillIDs(ids...)
}

// Mutation returns the BillStatusMutation object of the builder.
func (bsc *BillStatusCreate) Mutation() *BillStatusMutation {
	return bsc.mutation
}

// Save creates the BillStatus in the database.
func (bsc *BillStatusCreate) Save(ctx context.Context) (*BillStatus, error) {
	if _, ok := bsc.mutation.BillStatus(); !ok {
		return nil, &ValidationError{Name: "BillStatus", err: errors.New("ent: missing required field \"BillStatus\"")}
	}
	var (
		err  error
		node *BillStatus
	)
	if len(bsc.hooks) == 0 {
		node, err = bsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bsc.mutation = mutation
			node, err = bsc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bsc.hooks) - 1; i >= 0; i-- {
			mut = bsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bsc *BillStatusCreate) SaveX(ctx context.Context) *BillStatus {
	v, err := bsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bsc *BillStatusCreate) sqlSave(ctx context.Context) (*BillStatus, error) {
	bs, _spec := bsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bsc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	bs.ID = int(id)
	return bs, nil
}

func (bsc *BillStatusCreate) createSpec() (*BillStatus, *sqlgraph.CreateSpec) {
	var (
		bs    = &BillStatus{config: bsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: billstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: billstatus.FieldID,
			},
		}
	)
	if value, ok := bsc.mutation.BillStatus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: billstatus.FieldBillStatus,
		})
		bs.BillStatus = value
	}
	if nodes := bsc.mutation.BillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   billstatus.BillsTable,
			Columns: []string{billstatus.BillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return bs, _spec
}
