// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/theuo/app/ent/bill"
	"github.com/theuo/app/ent/billstatus"
	"github.com/theuo/app/ent/payment"
	"github.com/theuo/app/ent/user"
)

// Bill is the model entity for the Bill schema.
type Bill struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "Amount" field.
	Amount int `json:"Amount,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillQuery when eager-loading is set.
	Edges         BillEdges `json:"edges"`
	billstatus_id *int
	user_id       *int
}

// BillEdges holds the relations/edges for other nodes in the graph.
type BillEdges struct {
	// Billstatus holds the value of the billstatus edge.
	Billstatus *BillStatus
	// Payments holds the value of the payments edge.
	Payments *Payment
	// Resident holds the value of the resident edge.
	Resident *User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// BillstatusOrErr returns the Billstatus value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillEdges) BillstatusOrErr() (*BillStatus, error) {
	if e.loadedTypes[0] {
		if e.Billstatus == nil {
			// The edge billstatus was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: billstatus.Label}
		}
		return e.Billstatus, nil
	}
	return nil, &NotLoadedError{edge: "billstatus"}
}

// PaymentsOrErr returns the Payments value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillEdges) PaymentsOrErr() (*Payment, error) {
	if e.loadedTypes[1] {
		if e.Payments == nil {
			// The edge payments was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: payment.Label}
		}
		return e.Payments, nil
	}
	return nil, &NotLoadedError{edge: "payments"}
}

// ResidentOrErr returns the Resident value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BillEdges) ResidentOrErr() (*User, error) {
	if e.loadedTypes[2] {
		if e.Resident == nil {
			// The edge resident was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Resident, nil
	}
	return nil, &NotLoadedError{edge: "resident"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bill) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullInt64{}, // Amount
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Bill) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // billstatus_id
		&sql.NullInt64{}, // user_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bill fields.
func (b *Bill) assignValues(values ...interface{}) error {
	if m, n := len(values), len(bill.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	b.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field Amount", values[0])
	} else if value.Valid {
		b.Amount = int(value.Int64)
	}
	values = values[1:]
	if len(values) == len(bill.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field billstatus_id", value)
		} else if value.Valid {
			b.billstatus_id = new(int)
			*b.billstatus_id = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field user_id", value)
		} else if value.Valid {
			b.user_id = new(int)
			*b.user_id = int(value.Int64)
		}
	}
	return nil
}

// QueryBillstatus queries the billstatus edge of the Bill.
func (b *Bill) QueryBillstatus() *BillStatusQuery {
	return (&BillClient{config: b.config}).QueryBillstatus(b)
}

// QueryPayments queries the payments edge of the Bill.
func (b *Bill) QueryPayments() *PaymentQuery {
	return (&BillClient{config: b.config}).QueryPayments(b)
}

// QueryResident queries the resident edge of the Bill.
func (b *Bill) QueryResident() *UserQuery {
	return (&BillClient{config: b.config}).QueryResident(b)
}

// Update returns a builder for updating this Bill.
// Note that, you need to call Bill.Unwrap() before calling this method, if this Bill
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Bill) Update() *BillUpdateOne {
	return (&BillClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (b *Bill) Unwrap() *Bill {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bill is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Bill) String() string {
	var builder strings.Builder
	builder.WriteString("Bill(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteString(", Amount=")
	builder.WriteString(fmt.Sprintf("%v", b.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// Bills is a parsable slice of Bill.
type Bills []*Bill

func (b Bills) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
