// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/bill"
	"github.com/theuo/app/ent/billstatus"
	"github.com/theuo/app/ent/predicate"
)

// BillStatusQuery is the builder for querying BillStatus entities.
type BillStatusQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.BillStatus
	// eager-loading edges.
	withBills *BillQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (bsq *BillStatusQuery) Where(ps ...predicate.BillStatus) *BillStatusQuery {
	bsq.predicates = append(bsq.predicates, ps...)
	return bsq
}

// Limit adds a limit step to the query.
func (bsq *BillStatusQuery) Limit(limit int) *BillStatusQuery {
	bsq.limit = &limit
	return bsq
}

// Offset adds an offset step to the query.
func (bsq *BillStatusQuery) Offset(offset int) *BillStatusQuery {
	bsq.offset = &offset
	return bsq
}

// Order adds an order step to the query.
func (bsq *BillStatusQuery) Order(o ...OrderFunc) *BillStatusQuery {
	bsq.order = append(bsq.order, o...)
	return bsq
}

// QueryBills chains the current query on the bills edge.
func (bsq *BillStatusQuery) QueryBills() *BillQuery {
	query := &BillQuery{config: bsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billstatus.Table, billstatus.FieldID, bsq.sqlQuery()),
			sqlgraph.To(bill.Table, bill.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, billstatus.BillsTable, billstatus.BillsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BillStatus entity in the query. Returns *NotFoundError when no billstatus was found.
func (bsq *BillStatusQuery) First(ctx context.Context) (*BillStatus, error) {
	bsSlice, err := bsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(bsSlice) == 0 {
		return nil, &NotFoundError{billstatus.Label}
	}
	return bsSlice[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bsq *BillStatusQuery) FirstX(ctx context.Context) *BillStatus {
	bs, err := bsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return bs
}

// FirstID returns the first BillStatus id in the query. Returns *NotFoundError when no id was found.
func (bsq *BillStatusQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{billstatus.Label}
		return
	}
	return ids[0], nil
}

// FirstXID is like FirstID, but panics if an error occurs.
func (bsq *BillStatusQuery) FirstXID(ctx context.Context) int {
	id, err := bsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only BillStatus entity in the query, returns an error if not exactly one entity was returned.
func (bsq *BillStatusQuery) Only(ctx context.Context) (*BillStatus, error) {
	bsSlice, err := bsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(bsSlice) {
	case 1:
		return bsSlice[0], nil
	case 0:
		return nil, &NotFoundError{billstatus.Label}
	default:
		return nil, &NotSingularError{billstatus.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bsq *BillStatusQuery) OnlyX(ctx context.Context) *BillStatus {
	bs, err := bsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return bs
}

// OnlyID returns the only BillStatus id in the query, returns an error if not exactly one id was returned.
func (bsq *BillStatusQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = &NotSingularError{billstatus.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bsq *BillStatusQuery) OnlyIDX(ctx context.Context) int {
	id, err := bsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BillStatusSlice.
func (bsq *BillStatusQuery) All(ctx context.Context) ([]*BillStatus, error) {
	if err := bsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return bsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (bsq *BillStatusQuery) AllX(ctx context.Context) []*BillStatus {
	bsSlice, err := bsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return bsSlice
}

// IDs executes the query and returns a list of BillStatus ids.
func (bsq *BillStatusQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := bsq.Select(billstatus.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bsq *BillStatusQuery) IDsX(ctx context.Context) []int {
	ids, err := bsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bsq *BillStatusQuery) Count(ctx context.Context) (int, error) {
	if err := bsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return bsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (bsq *BillStatusQuery) CountX(ctx context.Context) int {
	count, err := bsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bsq *BillStatusQuery) Exist(ctx context.Context) (bool, error) {
	if err := bsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return bsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (bsq *BillStatusQuery) ExistX(ctx context.Context) bool {
	exist, err := bsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bsq *BillStatusQuery) Clone() *BillStatusQuery {
	return &BillStatusQuery{
		config:     bsq.config,
		limit:      bsq.limit,
		offset:     bsq.offset,
		order:      append([]OrderFunc{}, bsq.order...),
		unique:     append([]string{}, bsq.unique...),
		predicates: append([]predicate.BillStatus{}, bsq.predicates...),
		// clone intermediate query.
		sql:  bsq.sql.Clone(),
		path: bsq.path,
	}
}

//  WithBills tells the query-builder to eager-loads the nodes that are connected to
// the "bills" edge. The optional arguments used to configure the query builder of the edge.
func (bsq *BillStatusQuery) WithBills(opts ...func(*BillQuery)) *BillStatusQuery {
	query := &BillQuery{config: bsq.config}
	for _, opt := range opts {
		opt(query)
	}
	bsq.withBills = query
	return bsq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BillStatus string `json:"BillStatus,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BillStatus.Query().
//		GroupBy(billstatus.FieldBillStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (bsq *BillStatusQuery) GroupBy(field string, fields ...string) *BillStatusGroupBy {
	group := &BillStatusGroupBy{config: bsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := bsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return bsq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		BillStatus string `json:"BillStatus,omitempty"`
//	}
//
//	client.BillStatus.Query().
//		Select(billstatus.FieldBillStatus).
//		Scan(ctx, &v)
//
func (bsq *BillStatusQuery) Select(field string, fields ...string) *BillStatusSelect {
	selector := &BillStatusSelect{config: bsq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := bsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return bsq.sqlQuery(), nil
	}
	return selector
}

func (bsq *BillStatusQuery) prepareQuery(ctx context.Context) error {
	if bsq.path != nil {
		prev, err := bsq.path(ctx)
		if err != nil {
			return err
		}
		bsq.sql = prev
	}
	return nil
}

func (bsq *BillStatusQuery) sqlAll(ctx context.Context) ([]*BillStatus, error) {
	var (
		nodes       = []*BillStatus{}
		_spec       = bsq.querySpec()
		loadedTypes = [1]bool{
			bsq.withBills != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &BillStatus{config: bsq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, bsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := bsq.withBills; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*BillStatus)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
		}
		query.withFKs = true
		query.Where(predicate.Bill(func(s *sql.Selector) {
			s.Where(sql.InValues(billstatus.BillsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.billstatus_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "billstatus_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "billstatus_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Bills = append(node.Edges.Bills, n)
		}
	}

	return nodes, nil
}

func (bsq *BillStatusQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bsq.querySpec()
	return sqlgraph.CountNodes(ctx, bsq.driver, _spec)
}

func (bsq *BillStatusQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := bsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (bsq *BillStatusQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   billstatus.Table,
			Columns: billstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: billstatus.FieldID,
			},
		},
		From:   bsq.sql,
		Unique: true,
	}
	if ps := bsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bsq *BillStatusQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(bsq.driver.Dialect())
	t1 := builder.Table(billstatus.Table)
	selector := builder.Select(t1.Columns(billstatus.Columns...)...).From(t1)
	if bsq.sql != nil {
		selector = bsq.sql
		selector.Select(selector.Columns(billstatus.Columns...)...)
	}
	for _, p := range bsq.predicates {
		p(selector)
	}
	for _, p := range bsq.order {
		p(selector)
	}
	if offset := bsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BillStatusGroupBy is the builder for group-by BillStatus entities.
type BillStatusGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bsgb *BillStatusGroupBy) Aggregate(fns ...AggregateFunc) *BillStatusGroupBy {
	bsgb.fns = append(bsgb.fns, fns...)
	return bsgb
}

// Scan applies the group-by query and scan the result into the given value.
func (bsgb *BillStatusGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := bsgb.path(ctx)
	if err != nil {
		return err
	}
	bsgb.sql = query
	return bsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := bsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(bsgb.fields) > 1 {
		return nil, errors.New("ent: BillStatusGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := bsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) StringsX(ctx context.Context) []string {
	v, err := bsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) StringX(ctx context.Context) string {
	v, err := bsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(bsgb.fields) > 1 {
		return nil, errors.New("ent: BillStatusGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := bsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) IntsX(ctx context.Context) []int {
	v, err := bsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) IntX(ctx context.Context) int {
	v, err := bsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(bsgb.fields) > 1 {
		return nil, errors.New("ent: BillStatusGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := bsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := bsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) Float64X(ctx context.Context) float64 {
	v, err := bsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(bsgb.fields) > 1 {
		return nil, errors.New("ent: BillStatusGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := bsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := bsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (bsgb *BillStatusGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bsgb *BillStatusGroupBy) BoolX(ctx context.Context) bool {
	v, err := bsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bsgb *BillStatusGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bsgb.sqlQuery().Query()
	if err := bsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bsgb *BillStatusGroupBy) sqlQuery() *sql.Selector {
	selector := bsgb.sql
	columns := make([]string, 0, len(bsgb.fields)+len(bsgb.fns))
	columns = append(columns, bsgb.fields...)
	for _, fn := range bsgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(bsgb.fields...)
}

// BillStatusSelect is the builder for select fields of BillStatus entities.
type BillStatusSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (bss *BillStatusSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := bss.path(ctx)
	if err != nil {
		return err
	}
	bss.sql = query
	return bss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bss *BillStatusSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bss.fields) > 1 {
		return nil, errors.New("ent: BillStatusSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bss *BillStatusSelect) StringsX(ctx context.Context) []string {
	v, err := bss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bss *BillStatusSelect) StringX(ctx context.Context) string {
	v, err := bss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bss.fields) > 1 {
		return nil, errors.New("ent: BillStatusSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bss *BillStatusSelect) IntsX(ctx context.Context) []int {
	v, err := bss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bss *BillStatusSelect) IntX(ctx context.Context) int {
	v, err := bss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bss.fields) > 1 {
		return nil, errors.New("ent: BillStatusSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bss *BillStatusSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bss *BillStatusSelect) Float64X(ctx context.Context) float64 {
	v, err := bss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bss.fields) > 1 {
		return nil, errors.New("ent: BillStatusSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bss *BillStatusSelect) BoolsX(ctx context.Context) []bool {
	v, err := bss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (bss *BillStatusSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{billstatus.Label}
	default:
		err = fmt.Errorf("ent: BillStatusSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bss *BillStatusSelect) BoolX(ctx context.Context) bool {
	v, err := bss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bss *BillStatusSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bss.sqlQuery().Query()
	if err := bss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bss *BillStatusSelect) sqlQuery() sql.Querier {
	selector := bss.sql
	selector.Select(selector.Columns(bss.fields...)...)
	return selector
}
