// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/bill"
	"github.com/theuo/app/ent/billstatus"
	"github.com/theuo/app/ent/payment"
	"github.com/theuo/app/ent/user"
)

// BillCreate is the builder for creating a Bill entity.
type BillCreate struct {
	config
	mutation *BillMutation
	hooks    []Hook
}

// SetAmount sets the Amount field.
func (bc *BillCreate) SetAmount(i int) *BillCreate {
	bc.mutation.SetAmount(i)
	return bc
}

// SetBillstatusID sets the billstatus edge to BillStatus by id.
func (bc *BillCreate) SetBillstatusID(id int) *BillCreate {
	bc.mutation.SetBillstatusID(id)
	return bc
}

// SetNillableBillstatusID sets the billstatus edge to BillStatus by id if the given value is not nil.
func (bc *BillCreate) SetNillableBillstatusID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetBillstatusID(*id)
	}
	return bc
}

// SetBillstatus sets the billstatus edge to BillStatus.
func (bc *BillCreate) SetBillstatus(b *BillStatus) *BillCreate {
	return bc.SetBillstatusID(b.ID)
}

// SetPaymentsID sets the payments edge to Payment by id.
func (bc *BillCreate) SetPaymentsID(id int) *BillCreate {
	bc.mutation.SetPaymentsID(id)
	return bc
}

// SetNillablePaymentsID sets the payments edge to Payment by id if the given value is not nil.
func (bc *BillCreate) SetNillablePaymentsID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetPaymentsID(*id)
	}
	return bc
}

// SetPayments sets the payments edge to Payment.
func (bc *BillCreate) SetPayments(p *Payment) *BillCreate {
	return bc.SetPaymentsID(p.ID)
}

// SetResidentID sets the resident edge to User by id.
func (bc *BillCreate) SetResidentID(id int) *BillCreate {
	bc.mutation.SetResidentID(id)
	return bc
}

// SetNillableResidentID sets the resident edge to User by id if the given value is not nil.
func (bc *BillCreate) SetNillableResidentID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetResidentID(*id)
	}
	return bc
}

// SetResident sets the resident edge to User.
func (bc *BillCreate) SetResident(u *User) *BillCreate {
	return bc.SetResidentID(u.ID)
}

// Mutation returns the BillMutation object of the builder.
func (bc *BillCreate) Mutation() *BillMutation {
	return bc.mutation
}

// Save creates the Bill in the database.
func (bc *BillCreate) Save(ctx context.Context) (*Bill, error) {
	if _, ok := bc.mutation.Amount(); !ok {
		return nil, &ValidationError{Name: "Amount", err: errors.New("ent: missing required field \"Amount\"")}
	}
	var (
		err  error
		node *Bill
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BillCreate) SaveX(ctx context.Context) *Bill {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BillCreate) sqlSave(ctx context.Context) (*Bill, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BillCreate) createSpec() (*Bill, *sqlgraph.CreateSpec) {
	var (
		b     = &Bill{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bill.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bill.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldAmount,
		})
		b.Amount = value
	}
	if nodes := bc.mutation.BillstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.BillstatusTable,
			Columns: []string{bill.BillstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: billstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   bill.PaymentsTable,
			Columns: []string{bill.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: payment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.ResidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ResidentTable,
			Columns: []string{bill.ResidentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
