// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/billstatus"
	"github.com/theuo/app/ent/predicate"
)

// BillStatusDelete is the builder for deleting a BillStatus entity.
type BillStatusDelete struct {
	config
	hooks      []Hook
	mutation   *BillStatusMutation
	predicates []predicate.BillStatus
}

// Where adds a new predicate to the delete builder.
func (bsd *BillStatusDelete) Where(ps ...predicate.BillStatus) *BillStatusDelete {
	bsd.predicates = append(bsd.predicates, ps...)
	return bsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bsd *BillStatusDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bsd.hooks) == 0 {
		affected, err = bsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bsd.mutation = mutation
			affected, err = bsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bsd.hooks) - 1; i >= 0; i-- {
			mut = bsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bsd *BillStatusDelete) ExecX(ctx context.Context) int {
	n, err := bsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bsd *BillStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: billstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: billstatus.FieldID,
			},
		},
	}
	if ps := bsd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bsd.driver, _spec)
}

// BillStatusDeleteOne is the builder for deleting a single BillStatus entity.
type BillStatusDeleteOne struct {
	bsd *BillStatusDelete
}

// Exec executes the deletion query.
func (bsdo *BillStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := bsdo.bsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{billstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bsdo *BillStatusDeleteOne) ExecX(ctx context.Context) {
	bsdo.bsd.ExecX(ctx)
}
