// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/theuo/app/ent/bill"
	"github.com/theuo/app/ent/payment"
	"github.com/theuo/app/ent/paymentstatus"
	"github.com/theuo/app/ent/paytype"
	"github.com/theuo/app/ent/predicate"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks      []Hook
	mutation   *PaymentMutation
	predicates []predicate.Payment
}

// Where adds a new predicate for the builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetAddDatetime sets the AddDatetime field.
func (pu *PaymentUpdate) SetAddDatetime(t time.Time) *PaymentUpdate {
	pu.mutation.SetAddDatetime(t)
	return pu
}

// SetPaytypeID sets the paytype edge to PayType by id.
func (pu *PaymentUpdate) SetPaytypeID(id int) *PaymentUpdate {
	pu.mutation.SetPaytypeID(id)
	return pu
}

// SetNillablePaytypeID sets the paytype edge to PayType by id if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePaytypeID(id *int) *PaymentUpdate {
	if id != nil {
		pu = pu.SetPaytypeID(*id)
	}
	return pu
}

// SetPaytype sets the paytype edge to PayType.
func (pu *PaymentUpdate) SetPaytype(p *PayType) *PaymentUpdate {
	return pu.SetPaytypeID(p.ID)
}

// SetPaymentstatusID sets the paymentstatus edge to PaymentStatus by id.
func (pu *PaymentUpdate) SetPaymentstatusID(id int) *PaymentUpdate {
	pu.mutation.SetPaymentstatusID(id)
	return pu
}

// SetNillablePaymentstatusID sets the paymentstatus edge to PaymentStatus by id if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePaymentstatusID(id *int) *PaymentUpdate {
	if id != nil {
		pu = pu.SetPaymentstatusID(*id)
	}
	return pu
}

// SetPaymentstatus sets the paymentstatus edge to PaymentStatus.
func (pu *PaymentUpdate) SetPaymentstatus(p *PaymentStatus) *PaymentUpdate {
	return pu.SetPaymentstatusID(p.ID)
}

// SetBillID sets the bill edge to Bill by id.
func (pu *PaymentUpdate) SetBillID(id int) *PaymentUpdate {
	pu.mutation.SetBillID(id)
	return pu
}

// SetNillableBillID sets the bill edge to Bill by id if the given value is not nil.
func (pu *PaymentUpdate) SetNillableBillID(id *int) *PaymentUpdate {
	if id != nil {
		pu = pu.SetBillID(*id)
	}
	return pu
}

// SetBill sets the bill edge to Bill.
func (pu *PaymentUpdate) SetBill(b *Bill) *PaymentUpdate {
	return pu.SetBillID(b.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// ClearPaytype clears the paytype edge to PayType.
func (pu *PaymentUpdate) ClearPaytype() *PaymentUpdate {
	pu.mutation.ClearPaytype()
	return pu
}

// ClearPaymentstatus clears the paymentstatus edge to PaymentStatus.
func (pu *PaymentUpdate) ClearPaymentstatus() *PaymentUpdate {
	pu.mutation.ClearPaymentstatus()
	return pu
}

// ClearBill clears the bill edge to Bill.
func (pu *PaymentUpdate) ClearBill() *PaymentUpdate {
	pu.mutation.ClearBill()
	return pu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   payment.Table,
			Columns: payment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: payment.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.AddDatetime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: payment.FieldAddDatetime,
		})
	}
	if pu.mutation.PaytypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaytypeTable,
			Columns: []string{payment.PaytypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PaytypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaytypeTable,
			Columns: []string{payment.PaytypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.PaymentstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaymentstatusTable,
			Columns: []string{payment.PaymentstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paymentstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PaymentstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaymentstatusTable,
			Columns: []string{payment.PaymentstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paymentstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.BillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   payment.BillTable,
			Columns: []string{payment.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.BillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   payment.BillTable,
			Columns: []string{payment.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// SetAddDatetime sets the AddDatetime field.
func (puo *PaymentUpdateOne) SetAddDatetime(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetAddDatetime(t)
	return puo
}

// SetPaytypeID sets the paytype edge to PayType by id.
func (puo *PaymentUpdateOne) SetPaytypeID(id int) *PaymentUpdateOne {
	puo.mutation.SetPaytypeID(id)
	return puo
}

// SetNillablePaytypeID sets the paytype edge to PayType by id if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePaytypeID(id *int) *PaymentUpdateOne {
	if id != nil {
		puo = puo.SetPaytypeID(*id)
	}
	return puo
}

// SetPaytype sets the paytype edge to PayType.
func (puo *PaymentUpdateOne) SetPaytype(p *PayType) *PaymentUpdateOne {
	return puo.SetPaytypeID(p.ID)
}

// SetPaymentstatusID sets the paymentstatus edge to PaymentStatus by id.
func (puo *PaymentUpdateOne) SetPaymentstatusID(id int) *PaymentUpdateOne {
	puo.mutation.SetPaymentstatusID(id)
	return puo
}

// SetNillablePaymentstatusID sets the paymentstatus edge to PaymentStatus by id if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePaymentstatusID(id *int) *PaymentUpdateOne {
	if id != nil {
		puo = puo.SetPaymentstatusID(*id)
	}
	return puo
}

// SetPaymentstatus sets the paymentstatus edge to PaymentStatus.
func (puo *PaymentUpdateOne) SetPaymentstatus(p *PaymentStatus) *PaymentUpdateOne {
	return puo.SetPaymentstatusID(p.ID)
}

// SetBillID sets the bill edge to Bill by id.
func (puo *PaymentUpdateOne) SetBillID(id int) *PaymentUpdateOne {
	puo.mutation.SetBillID(id)
	return puo
}

// SetNillableBillID sets the bill edge to Bill by id if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableBillID(id *int) *PaymentUpdateOne {
	if id != nil {
		puo = puo.SetBillID(*id)
	}
	return puo
}

// SetBill sets the bill edge to Bill.
func (puo *PaymentUpdateOne) SetBill(b *Bill) *PaymentUpdateOne {
	return puo.SetBillID(b.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// ClearPaytype clears the paytype edge to PayType.
func (puo *PaymentUpdateOne) ClearPaytype() *PaymentUpdateOne {
	puo.mutation.ClearPaytype()
	return puo
}

// ClearPaymentstatus clears the paymentstatus edge to PaymentStatus.
func (puo *PaymentUpdateOne) ClearPaymentstatus() *PaymentUpdateOne {
	puo.mutation.ClearPaymentstatus()
	return puo
}

// ClearBill clears the bill edge to Bill.
func (puo *PaymentUpdateOne) ClearBill() *PaymentUpdateOne {
	puo.mutation.ClearBill()
	return puo
}

// Save executes the query and returns the updated entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {

	var (
		err  error
		node *Payment
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	pa, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pa
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (pa *Payment, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   payment.Table,
			Columns: payment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: payment.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Payment.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.AddDatetime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: payment.FieldAddDatetime,
		})
	}
	if puo.mutation.PaytypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaytypeTable,
			Columns: []string{payment.PaytypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paytype.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PaytypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaytypeTable,
			Columns: []string{payment.PaytypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.PaymentstatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaymentstatusTable,
			Columns: []string{payment.PaymentstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paymentstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PaymentstatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.PaymentstatusTable,
			Columns: []string{payment.PaymentstatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: paymentstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.BillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   payment.BillTable,
			Columns: []string{payment.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.BillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   payment.BillTable,
			Columns: []string{payment.BillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pa = &Payment{config: puo.config}
	_spec.Assign = pa.assignValues
	_spec.ScanValues = pa.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pa, nil
}
