// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/theuo/app/ent/paymentstatus"
)

// PaymentStatus is the model entity for the PaymentStatus schema.
type PaymentStatus struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PaymentStatus holds the value of the "PaymentStatus" field.
	PaymentStatus string `json:"PaymentStatus,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentStatusQuery when eager-loading is set.
	Edges PaymentStatusEdges `json:"edges"`
}

// PaymentStatusEdges holds the relations/edges for other nodes in the graph.
type PaymentStatusEdges struct {
	// Payments holds the value of the payments edge.
	Payments []*Payment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentsOrErr returns the Payments value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentStatusEdges) PaymentsOrErr() ([]*Payment, error) {
	if e.loadedTypes[0] {
		return e.Payments, nil
	}
	return nil, &NotLoadedError{edge: "payments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentStatus) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // PaymentStatus
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentStatus fields.
func (ps *PaymentStatus) assignValues(values ...interface{}) error {
	if m, n := len(values), len(paymentstatus.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ps.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field PaymentStatus", values[0])
	} else if value.Valid {
		ps.PaymentStatus = value.String
	}
	return nil
}

// QueryPayments queries the payments edge of the PaymentStatus.
func (ps *PaymentStatus) QueryPayments() *PaymentQuery {
	return (&PaymentStatusClient{config: ps.config}).QueryPayments(ps)
}

// Update returns a builder for updating this PaymentStatus.
// Note that, you need to call PaymentStatus.Unwrap() before calling this method, if this PaymentStatus
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *PaymentStatus) Update() *PaymentStatusUpdateOne {
	return (&PaymentStatusClient{config: ps.config}).UpdateOne(ps)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ps *PaymentStatus) Unwrap() *PaymentStatus {
	tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentStatus is not a transactional entity")
	}
	ps.config.driver = tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *PaymentStatus) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentStatus(")
	builder.WriteString(fmt.Sprintf("id=%v", ps.ID))
	builder.WriteString(", PaymentStatus=")
	builder.WriteString(ps.PaymentStatus)
	builder.WriteByte(')')
	return builder.String()
}

// PaymentStatusSlice is a parsable slice of PaymentStatus.
type PaymentStatusSlice []*PaymentStatus

func (ps PaymentStatusSlice) config(cfg config) {
	for _i := range ps {
		ps[_i].config = cfg
	}
}
