// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BillsColumns holds the columns for the "bills" table.
	BillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt},
		{Name: "billstatus_id", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt, Nullable: true},
	}
	// BillsTable holds the schema information for the "bills" table.
	BillsTable = &schema.Table{
		Name:       "bills",
		Columns:    BillsColumns,
		PrimaryKey: []*schema.Column{BillsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "bills_bill_status_bills",
				Columns: []*schema.Column{BillsColumns[2]},

				RefColumns: []*schema.Column{BillStatusColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "bills_users_bills",
				Columns: []*schema.Column{BillsColumns[3]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BillStatusColumns holds the columns for the "bill_status" table.
	BillStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bill_status", Type: field.TypeString, Unique: true},
	}
	// BillStatusTable holds the schema information for the "bill_status" table.
	BillStatusTable = &schema.Table{
		Name:        "bill_status",
		Columns:     BillStatusColumns,
		PrimaryKey:  []*schema.Column{BillStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PayTypesColumns holds the columns for the "pay_types" table.
	PayTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type_info", Type: field.TypeString, Unique: true},
	}
	// PayTypesTable holds the schema information for the "pay_types" table.
	PayTypesTable = &schema.Table{
		Name:        "pay_types",
		Columns:     PayTypesColumns,
		PrimaryKey:  []*schema.Column{PayTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "add_datetime", Type: field.TypeTime},
		{Name: "bill_id", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "paytype_id", Type: field.TypeInt, Nullable: true},
		{Name: "paymentstatus_id", Type: field.TypeInt, Nullable: true},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "payments_bills_payments",
				Columns: []*schema.Column{PaymentsColumns[2]},

				RefColumns: []*schema.Column{BillsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "payments_pay_types_payments",
				Columns: []*schema.Column{PaymentsColumns[3]},

				RefColumns: []*schema.Column{PayTypesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "payments_payment_status_payments",
				Columns: []*schema.Column{PaymentsColumns[4]},

				RefColumns: []*schema.Column{PaymentStatusColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PaymentStatusColumns holds the columns for the "payment_status" table.
	PaymentStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "payment_status", Type: field.TypeString, Unique: true},
	}
	// PaymentStatusTable holds the schema information for the "payment_status" table.
	PaymentStatusTable = &schema.Table{
		Name:        "payment_status",
		Columns:     PaymentStatusColumns,
		PrimaryKey:  []*schema.Column{PaymentStatusColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BillsTable,
		BillStatusTable,
		PayTypesTable,
		PaymentsTable,
		PaymentStatusTable,
		UsersTable,
	}
)

func init() {
	BillsTable.ForeignKeys[0].RefTable = BillStatusTable
	BillsTable.ForeignKeys[1].RefTable = UsersTable
	PaymentsTable.ForeignKeys[0].RefTable = BillsTable
	PaymentsTable.ForeignKeys[1].RefTable = PayTypesTable
	PaymentsTable.ForeignKeys[2].RefTable = PaymentStatusTable
}
