// Code generated by entc, DO NOT EDIT.

package paytype

const (
	// Label holds the string label denoting the paytype type in the database.
	Label = "pay_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTypeInfo holds the string denoting the typeinfo field in the database.
	FieldTypeInfo = "type_info"

	// EdgePayments holds the string denoting the payments edge name in mutations.
	EdgePayments = "payments"

	// Table holds the table name of the paytype in the database.
	Table = "pay_types"
	// PaymentsTable is the table the holds the payments relation/edge.
	PaymentsTable = "payments"
	// PaymentsInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	PaymentsInverseTable = "payments"
	// PaymentsColumn is the table column denoting the payments relation/edge.
	PaymentsColumn = "paytype_id"
)

// Columns holds all SQL columns for paytype fields.
var Columns = []string{
	FieldID,
	FieldTypeInfo,
}

var (
	// TypeInfoValidator is a validator for the "TypeInfo" field. It is called by the builders before save.
	TypeInfoValidator func(string) error
)
