// Code generated by entc, DO NOT EDIT.

package paytype

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/theuo/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TypeInfo applies equality check predicate on the "TypeInfo" field. It's identical to TypeInfoEQ.
func TypeInfo(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoEQ applies the EQ predicate on the "TypeInfo" field.
func TypeInfoEQ(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoNEQ applies the NEQ predicate on the "TypeInfo" field.
func TypeInfoNEQ(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoIn applies the In predicate on the "TypeInfo" field.
func TypeInfoIn(vs ...string) predicate.PayType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PayType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTypeInfo), v...))
	})
}

// TypeInfoNotIn applies the NotIn predicate on the "TypeInfo" field.
func TypeInfoNotIn(vs ...string) predicate.PayType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PayType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTypeInfo), v...))
	})
}

// TypeInfoGT applies the GT predicate on the "TypeInfo" field.
func TypeInfoGT(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoGTE applies the GTE predicate on the "TypeInfo" field.
func TypeInfoGTE(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoLT applies the LT predicate on the "TypeInfo" field.
func TypeInfoLT(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoLTE applies the LTE predicate on the "TypeInfo" field.
func TypeInfoLTE(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoContains applies the Contains predicate on the "TypeInfo" field.
func TypeInfoContains(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoHasPrefix applies the HasPrefix predicate on the "TypeInfo" field.
func TypeInfoHasPrefix(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoHasSuffix applies the HasSuffix predicate on the "TypeInfo" field.
func TypeInfoHasSuffix(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoEqualFold applies the EqualFold predicate on the "TypeInfo" field.
func TypeInfoEqualFold(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTypeInfo), v))
	})
}

// TypeInfoContainsFold applies the ContainsFold predicate on the "TypeInfo" field.
func TypeInfoContainsFold(v string) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTypeInfo), v))
	})
}

// HasPayments applies the HasEdge predicate on the "payments" edge.
func HasPayments() predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentsWith applies the HasEdge predicate on the "payments" edge with a given conditions (other predicates).
func HasPaymentsWith(preds ...predicate.Payment) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentsTable, PaymentsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.PayType) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.PayType) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PayType) predicate.PayType {
	return predicate.PayType(func(s *sql.Selector) {
		p(s.Not())
	})
}
