/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPayment
 */
export interface ControllersPayment {
    /**
     * 
     * @type {string}
     * @memberof ControllersPayment
     */
    addDatetime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    bill?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    payType?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    paymentStatus?: number;
}

export function ControllersPaymentFromJSON(json: any): ControllersPayment {
    return ControllersPaymentFromJSONTyped(json, false);
}

export function ControllersPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPayment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addDatetime': !exists(json, 'addDatetime') ? undefined : json['addDatetime'],
        'bill': !exists(json, 'bill') ? undefined : json['bill'],
        'payType': !exists(json, 'payType') ? undefined : json['payType'],
        'paymentStatus': !exists(json, 'paymentStatus') ? undefined : json['paymentStatus'],
    };
}

export function ControllersPaymentToJSON(value?: ControllersPayment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addDatetime': value.addDatetime,
        'bill': value.bill,
        'payType': value.payType,
        'paymentStatus': value.paymentStatus,
    };
}


