/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBillStatusEdges
 */
export interface EntBillStatusEdges {
    /**
     * Bills holds the value of the bills edge.
     * @type {Array<EntBill>}
     * @memberof EntBillStatusEdges
     */
    bills?: Array<EntBill>;
}

export function EntBillStatusEdgesFromJSON(json: any): EntBillStatusEdges {
    return EntBillStatusEdgesFromJSONTyped(json, false);
}

export function EntBillStatusEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBillStatusEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bills': !exists(json, 'Bills') ? undefined : ((json['Bills'] as Array<any>).map(EntBillFromJSON)),
    };
}

export function EntBillStatusEdgesToJSON(value?: EntBillStatusEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bills': value.bills === undefined ? undefined : ((value.bills as Array<any>).map(EntBillToJSON)),
    };
}


