/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPayment,
    EntPaymentFromJSON,
    EntPaymentFromJSONTyped,
    EntPaymentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPaymentStatusEdges
 */
export interface EntPaymentStatusEdges {
    /**
     * Payments holds the value of the payments edge.
     * @type {Array<EntPayment>}
     * @memberof EntPaymentStatusEdges
     */
    payments?: Array<EntPayment>;
}

export function EntPaymentStatusEdgesFromJSON(json: any): EntPaymentStatusEdges {
    return EntPaymentStatusEdgesFromJSONTyped(json, false);
}

export function EntPaymentStatusEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPaymentStatusEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'payments': !exists(json, 'Payments') ? undefined : ((json['Payments'] as Array<any>).map(EntPaymentFromJSON)),
    };
}

export function EntPaymentStatusEdgesToJSON(value?: EntPaymentStatusEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'payments': value.payments === undefined ? undefined : ((value.payments as Array<any>).map(EntPaymentToJSON)),
    };
}


