/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPaymentStatusEdges,
    EntPaymentStatusEdgesFromJSON,
    EntPaymentStatusEdgesFromJSONTyped,
    EntPaymentStatusEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPaymentStatus
 */
export interface EntPaymentStatus {
    /**
     * PaymentStatus holds the value of the "PaymentStatus" field.
     * @type {string}
     * @memberof EntPaymentStatus
     */
    paymentStatus?: string;
    /**
     * 
     * @type {EntPaymentStatusEdges}
     * @memberof EntPaymentStatus
     */
    edges?: EntPaymentStatusEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPaymentStatus
     */
    id?: number;
}

export function EntPaymentStatusFromJSON(json: any): EntPaymentStatus {
    return EntPaymentStatusFromJSONTyped(json, false);
}

export function EntPaymentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPaymentStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentStatus': !exists(json, 'PaymentStatus') ? undefined : json['PaymentStatus'],
        'edges': !exists(json, 'edges') ? undefined : EntPaymentStatusEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPaymentStatusToJSON(value?: EntPaymentStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PaymentStatus': value.paymentStatus,
        'edges': EntPaymentStatusEdgesToJSON(value.edges),
        'id': value.id,
    };
}


