/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPayTypeEdges,
    EntPayTypeEdgesFromJSON,
    EntPayTypeEdgesFromJSONTyped,
    EntPayTypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPayType
 */
export interface EntPayType {
    /**
     * TypeInfo holds the value of the "TypeInfo" field.
     * @type {string}
     * @memberof EntPayType
     */
    typeInfo?: string;
    /**
     * 
     * @type {EntPayTypeEdges}
     * @memberof EntPayType
     */
    edges?: EntPayTypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPayType
     */
    id?: number;
}

export function EntPayTypeFromJSON(json: any): EntPayType {
    return EntPayTypeFromJSONTyped(json, false);
}

export function EntPayTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPayType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'typeInfo': !exists(json, 'TypeInfo') ? undefined : json['TypeInfo'],
        'edges': !exists(json, 'edges') ? undefined : EntPayTypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPayTypeToJSON(value?: EntPayType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TypeInfo': value.typeInfo,
        'edges': EntPayTypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


