/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBill,
    EntBillFromJSON,
    EntBillFromJSONTyped,
    EntBillToJSON,
    EntPayType,
    EntPayTypeFromJSON,
    EntPayTypeFromJSONTyped,
    EntPayTypeToJSON,
    EntPaymentStatus,
    EntPaymentStatusFromJSON,
    EntPaymentStatusFromJSONTyped,
    EntPaymentStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPaymentEdges
 */
export interface EntPaymentEdges {
    /**
     * 
     * @type {EntBill}
     * @memberof EntPaymentEdges
     */
    bill?: EntBill;
    /**
     * 
     * @type {EntPaymentStatus}
     * @memberof EntPaymentEdges
     */
    paymentstatus?: EntPaymentStatus;
    /**
     * 
     * @type {EntPayType}
     * @memberof EntPaymentEdges
     */
    paytype?: EntPayType;
}

export function EntPaymentEdgesFromJSON(json: any): EntPaymentEdges {
    return EntPaymentEdgesFromJSONTyped(json, false);
}

export function EntPaymentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPaymentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bill': !exists(json, 'Bill') ? undefined : EntBillFromJSON(json['Bill']),
        'paymentstatus': !exists(json, 'Paymentstatus') ? undefined : EntPaymentStatusFromJSON(json['Paymentstatus']),
        'paytype': !exists(json, 'Paytype') ? undefined : EntPayTypeFromJSON(json['Paytype']),
    };
}

export function EntPaymentEdgesToJSON(value?: EntPaymentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bill': EntBillToJSON(value.bill),
        'paymentstatus': EntPaymentStatusToJSON(value.paymentstatus),
        'paytype': EntPayTypeToJSON(value.paytype),
    };
}


