// Code generated by entc, DO NOT EDIT.

package bill

const (
	// Label holds the string label denoting the bill type in the database.
	Label = "bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"

	// EdgeBillstatus holds the string denoting the billstatus edge name in mutations.
	EdgeBillstatus = "billstatus"
	// EdgePayments holds the string denoting the payments edge name in mutations.
	EdgePayments = "payments"
	// EdgeResident holds the string denoting the resident edge name in mutations.
	EdgeResident = "resident"

	// Table holds the table name of the bill in the database.
	Table = "bills"
	// BillstatusTable is the table the holds the billstatus relation/edge.
	BillstatusTable = "bills"
	// BillstatusInverseTable is the table name for the BillStatus entity.
	// It exists in this package in order to avoid circular dependency with the "billstatus" package.
	BillstatusInverseTable = "bill_status"
	// BillstatusColumn is the table column denoting the billstatus relation/edge.
	BillstatusColumn = "billstatus_id"
	// PaymentsTable is the table the holds the payments relation/edge.
	PaymentsTable = "payments"
	// PaymentsInverseTable is the table name for the Payment entity.
	// It exists in this package in order to avoid circular dependency with the "payment" package.
	PaymentsInverseTable = "payments"
	// PaymentsColumn is the table column denoting the payments relation/edge.
	PaymentsColumn = "bill_id"
	// ResidentTable is the table the holds the resident relation/edge.
	ResidentTable = "bills"
	// ResidentInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ResidentInverseTable = "users"
	// ResidentColumn is the table column denoting the resident relation/edge.
	ResidentColumn = "user_id"
)

// Columns holds all SQL columns for bill fields.
var Columns = []string{
	FieldID,
	FieldAmount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Bill type.
var ForeignKeys = []string{
	"billstatus_id",
	"user_id",
}
